name: windows_build
on:
  pull_request:
  release:
    types:
      - published
  push:
    tags: ["*"]
    branches:
      - main
      - dev
# env:
defaults:
  run:
    shell: powershell
jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
        compiler:
          - msvc
        cmake_preset:
          - "windows-msvc-debug-developer-mode"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          cmake_preset: ${{ matrix.cmake_preset }}

      - name: Setup Tools
        working-directory: ./scripts
        run: |
          ./setup.bat

      - name: Project setup
        run: |
          tsx project.mts setup ${{matrix.cmake_preset}}

      - name: Cmake configure
        run: |
          tsx project.mts config

      - name: Cmake build
        run: |
          tsx project.mts build

      - name: Cmake test
        run: |
          tsx project.mts test

      - name: Cmake install
        run: |
          tsx project.mts install

      - name: Cmake pack
        run: |
          tsx project.mts pack

      - name: Publish Tagged Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            ./out/build/${{matrix.cmake_preset}}/*-*${{ matrix.build_type }}*-*.*

      - name: Publish to codecov
        uses: codecov/codecov-action@v4
        with:
          flags: ${{ runner.os }}
          name: ${{ runner.os }}-coverage
          files: ./out/coverage/coverage.xml
          verbose: true # optional (default = false)
